"""empty message

Revision ID: 1a1e0c395ff3
Revises: a524f97f269b
Create Date: 2017-06-18 14:42:37.036000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1e0c395ff3'
down_revision = 'a524f97f269b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'create_time')
    # ### end Alembic commands ###
